### ISSUE TITLE
Open recent shows no recent projects

### ISSUE THREAD

**Issue by thomsong** [scrowl-io/authoring#111]
The recents list is empty

<img width="363" alt="image" src="https://user-images.githubusercontent.com/999242/205710978-d1d5e8a2-941d-41e9-ab73-9a43e69354ee.png">

**Comment by aubeOSG** [comment]
![Screen Shot 2022-12-05 at 1 18 05 PM](https://user-images.githubusercontent.com/94341482/205712444-01f7b8f7-1c5c-41f8-b479-a32f896f7221.png)

I'm able to see a list of up to the 5 most recent projects.

Maybe this is a result of a weird interaction of deleting the scrowl folder #102 ?

**Comment by thomsong** [comment]
I found the issue. I had to restart the editor before the "recents" got populated. It should refresh/populate once you close/save a project, not just on reload.
