### ISSUE TITLE
File open dialog is not modal

### ISSUE THREAD

**Issue by thomsong** [scrowl-io/authoring#140]
When adding a new file to the project files, the select file dialog is not "on top"/modal, and can go behind the Scrowl window and get lost.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/999242/206217427-7dc31eef-e2f7-4657-9583-76e2616367fd.png">

**Comment by aubeOSG** [comment]
closed by pull #170

**Comment by thomsong** [comment]
The project Save dialog is not modal. ALL system dialogs should be modal.
